version: "3.3"
services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
