version: "3.1"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - ${PORT}:80
    volumes:
      - data_conf:/etc/nginx/conf.d

volumes:
  data_conf:
