version: "3.1"

services:
  fava:
    image: beancount-fava
    container_name: beancount-fava
    build: .
    restart: always
    ports:
      - 5555:5000
    volumes:
      - ./data:/bean
    environment:
      BEANCOUNT_FILE: /bean/main.bean
  cron:
    image: beancount-cron
    container_name: beancount-cron
    build:
      context: .
      dockerfile: price.Dockerfile
    restart: unless-stopped
    volumes:
      - ./data/price:/root/price
