version: "3"
services:
  shiori:
    image: ghcr.io/go-shiori/shiori
    container_name: shiori
    restart: always
    ports:
      - ${PORT}:8080
    volumes:
      - data:/shiori
    command: serve

volumes:
  data:
