version: "3.9"

services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: always
    network_mode: host
    command: tunnel --no-autoupdate run --token ${TOKEN}
