version: "3.8"

services:
  mysql:
    # platform: linux/x86_64
    image: mysql:${IMAGE_TAG}
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PORT}:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
