version: "3.8"

services:
  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${PORT}:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
